// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkUHm6qMFrC2HACLeY8Z5tqRb4P0GI0A0',
    appId: '1:140416620839:web:22998d64899984b198f102',
    messagingSenderId: '140416620839',
    projectId: 'instagram-clone-102dc',
    authDomain: 'instagram-clone-102dc.firebaseapp.com',
    storageBucket: 'instagram-clone-102dc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwmK-q-9vY2EF9aLYIu9Qa8fTxwoygTe0',
    appId: '1:140416620839:android:d2354ca7d6c3659598f102',
    messagingSenderId: '140416620839',
    projectId: 'instagram-clone-102dc',
    storageBucket: 'instagram-clone-102dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeJRlQkNWEp3tgIeYWqdzhOmidZEdhYbY',
    appId: '1:140416620839:ios:13d4d3ca59a4031198f102',
    messagingSenderId: '140416620839',
    projectId: 'instagram-clone-102dc',
    storageBucket: 'instagram-clone-102dc.appspot.com',
    iosBundleId: 'com.example.instaClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeJRlQkNWEp3tgIeYWqdzhOmidZEdhYbY',
    appId: '1:140416620839:ios:ab16f49376bb974198f102',
    messagingSenderId: '140416620839',
    projectId: 'instagram-clone-102dc',
    storageBucket: 'instagram-clone-102dc.appspot.com',
    iosBundleId: 'com.example.instaClone.RunnerTests',
  );
}
