spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        format_sql: true
#        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

  datasource:
    url: jdbc:h2:mem:tes;MODE=PostgreSQL;NON_KEYWORDS=USER
    username: sa
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

  output:
    ansi:
      enabled: always

authentication:
  access-token:
    secretKey: ${JWT_SECRET}

ai:
  server-url: "http://3.34.179.78:8080/ai/certification"

logging:
  level:
    org.springframework.web.socket.config.WebSocketMessageBrokerStats: ERROR
#server:
#  error:
#    include-message: always

