-- IMAGE 테이블
CREATE TABLE IMAGE (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       url VARCHAR(255) NOT NULL
);
-- USER 테이블
CREATE TABLE USER (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      authentication_type VARCHAR(255),
                      email VARCHAR(255) UNIQUE,
                      name VARCHAR(255),
                      mileage INTEGER,
                      introduce_message VARCHAR(255),
                      image_id BIGINT,
                      FOREIGN KEY (image_id) REFERENCES IMAGE(id)
);

CREATE TABLE PASSWORD_AUTHENTICATION (
                                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         user_id BIGINT,
                                         password VARCHAR(255),
                                         FOREIGN KEY (user_id) REFERENCES USER(id)
);

-- ROOM 테이블
CREATE TABLE ROOM (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      name VARCHAR(255),
                      password VARCHAR(255),
                      info VARCHAR(255),
                      notice VARCHAR(255),
                      end_day TIMESTAMP,
                      max_user BIGINT DEFAULT 50,
                      now_user BIGINT,
                      can_chat BOOLEAN,
                      num_of_vote_success INTEGER,
                      num_of_vote_fail INTEGER,
                      is_full BOOLEAN,
                      num_of_goal INTEGER,
                      now_goal INTEGER,
                      image_id BIGINT,
                      periodicity VARCHAR(255),
                      frequency INTEGER,
                      certification_type VARCHAR(255),
                      room_type VARCHAR(255),
                      category VARCHAR(255),
                      FOREIGN KEY (image_id) REFERENCES IMAGE(id)
);

-- ROOM_GOALS 테이블
CREATE TABLE ROOM_GOALS (
                            room_id BIGINT,
                            goal VARCHAR(255),
                            PRIMARY KEY (room_id, goal),
                            FOREIGN KEY (room_id) REFERENCES ROOM(id)
);

-- ROOM_USER 테이블
CREATE TABLE ROOM_USER (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           is_manager BOOLEAN DEFAULT FALSE,
                           certificate_time INTEGER DEFAULT 0,
                           user_id BIGINT,
                           created_time TIMESTAMP,
                           room_id BIGINT,
                           FOREIGN KEY (user_id) REFERENCES USER(id),
                           FOREIGN KEY (room_id) REFERENCES ROOM(id)
);

-- CERTIFICATION 테이블
CREATE TABLE CERTIFICATION (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               room_user_id BIGINT,
                               status VARCHAR(255),
                               created_time TIMESTAMP,
                               image_id BIGINT,
                               vote_up INTEGER,
                               vote_down INTEGER,
                               FOREIGN KEY (room_user_id) REFERENCES ROOM_USER(id),
                               FOREIGN KEY (image_id) REFERENCES IMAGE(id)
);

-- VOTE 테이블
CREATE TABLE VOTE (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      user_id BIGINT,
                      vote_status VARCHAR(255),
                      certification_id BIGINT,
                      FOREIGN KEY (user_id) REFERENCES USER(id),
                      FOREIGN KEY (certification_id) REFERENCES CERTIFICATION(id)
);

-- MESSAGE 테이블
CREATE TABLE MESSAGE (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         room_id BIGINT,
                         user_id BIGINT,
                         message TEXT,
                         time TIMESTAMP
);

-- CREATURE 테이블
CREATE TABLE CREATURE (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(255),
                          price INTEGER,
                          info VARCHAR(255),
                          image_id BIGINT,
                          FOREIGN KEY (image_id) REFERENCES IMAGE(id)
);

-- SEA_CREATURE 테이블
CREATE TABLE SEA_CREATURE (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              coordinate_x BIGINT,
                              coordinate_y BIGINT,
                              is_activate BOOLEAN,
                              user_id BIGINT,
                              creature_id BIGINT,
                              FOREIGN KEY (user_id) REFERENCES USER(id),
                              FOREIGN KEY (creature_id) REFERENCES CREATURE(id)
);

-- TAG 테이블
CREATE TABLE TAG (
                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     name VARCHAR(255)
);

-- ROOM_TAG 테이블
CREATE TABLE ROOM_TAG (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          room_id BIGINT,
                          tag_id BIGINT,
                          FOREIGN KEY (room_id) REFERENCES ROOM(id),
                          FOREIGN KEY (tag_id) REFERENCES TAG(id)
);

